# Generated by Django 5.0.6 on 2024-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Bkash', 'Bkash')], default='Cash on delivery', max_length=30),
        ),
    ]
